/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rtbkit_Handle */

#ifndef _Included_rtbkit_Handle
#define _Included_rtbkit_Handle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rtbkit_Handle
 * Method:    initialize
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_rtbkit_Handle_initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     rtbkit_Handle
 * Method:    shutdown
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_rtbkit_Handle_shutdown
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
