/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rtbkit_Object */

#ifndef _Included_rtbkit_Object
#define _Included_rtbkit_Object
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rtbkit_Object
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_rtbkit_Object_release
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
